version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 18
        - nvm use 18
        - corepack enable
        - npm install --frozen-lockfile # or npm ci if using npm
    build:
      commands:
        - npm build
        - npm export
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
